export const KEY_WORDS = [
  'vagas para freelancer',
  'copywriter freelancer',
  'freelancer df',
  'trabalho freelance',
  'freelance 24 horas ',
  'freelance designer',
  'vaga freelancer home office',
  'freelancer marketing',
  'freelancer redator',
  'portal freelance',
  'designer freelancer',
  'freelancer design',
  'web designer freelancer',
  'vaga freelancer sp',
  'escritor freelancer',
  'freelance design',
  'plataforma freelancer',
  'como trabalhar de freelancer',
  'fotografo freelancer',
  'trabalho freelancer rj',
  'advogado freelancer',
  'emprego freelancer',
  'trabalho freelancer online',
  'design freelance',
  'freelancer design grafico',
  'freelancer ti',
  'workana freelancer',
  'plataforma de freelancers',
  'freelance python',
  'freelancer php',
  'freelancer tradutor',
  'desenhista freelancer',
  'freelance arquitetura',
  'freelancer contabilidade',
  'redator freelancer vagas',
  'freelancer digitador',
  'tradutor freelancer',
  'freelancer designer',
  'site para freelancers',
  'freelancer java',
  'freelancer trabalhos',
  'logo freelancer',
  'como trabalhar como freelancer',
  'servico de freelancer',
  'trabalhos de freelancer',
  'freelancer logo',
  'vendedor freelancer',
  'contratar freelancer',
  'freelancer jornalista',
  'freelancer designer grafico',
  'desenvolvedor web freelancer',
  'trabalhar freelancer online',
  'freelancer salvador',
  'agencias freelancer',
  'freelancer web',
  'design grafico freelancer',
  'programador php freelancer',
  'freelancer seo',
  'fotografia freelancer',
  'serviço freelancer',
  'trabalhos como freelancer',
  'sites freelancer',
  'trabalho freelancer home office',
  'arquiteto freelancer',
  'contratar redator freelancer',
  'freelance design gráfico',
  'freelance php',
  'freelancer android',
  'freelancer delphi',
  'freelancer desenvolvimento',
  'freelancer diagramação',
  'freelancer engenharia',
  'freelancer midias sociais',
  'freelancer redes sociais',
  'revisor de texto freelance',
  'trabalho com freelancer',
  'wordpress freelancer',
  'desenvolvedor php freelancer',
  'editor de videos freelancer',
  'freelance tradução',
  'freelance wordpress',
  'freelancer desenvolvedor web',
  'freelancer wordpress',
  'projetos freelancer',
  'trabalhos para freelancer',
  'designer freelancer precisa se',
  'empresa freelancer',
  'fotografo freelancer sp',
  'serviços freelancer de digitação',
  'site freelancers brasil',
  'trabalhar de freelancer online',
  'trabalhe freelancer online',
  'freelancer 99',
  'freelancer sites',
  'plataforma freelancers',
  'freelancer home office digitador',
  'freelancer autocad',
  'melhores sites para frellancer',
  'consultor',
  'especialista',
  'coach',
  'mentor',
  'free las',
  'assitente virtual',
  'site de freelas',
  'ebook plrs',
  'site para designer freelancer',
  'Nomade digital',
  'especialista frellancer',
  'consultor frellance',
  'coach frellancer',
  'mentor frellancer',
  'Job frellancer'
]
