export const typeFile = [
  'application/pdf',
  'image/jpeg',
  'image/png',
  'image/jpg',
  'image/ms-excel',
  'image/ms-powerpoint',
  'image/ms-word',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/plain',
  'application/vnd.ms-powerpoint',
  'application/vnd.ms-excel',
  'application/msword',
];
