

export const itens = [
  {
    score: 1,
    id: 1,
    nome: "Projeto Morning Show",
    descricao: "Uma descrição detalhada do projeto aqui",
    areaInteresse: "Tecnologia da Informação",
    subareas: ["Desenvolvimento Web", "Desenvolvimento Mobile"],
    nivelExperiencia: "ESPECIALISTA",
    habilidadesExigidas: ["Node.js", "Javascript"],
    dataInicioEstimada: "2022-01-01",
    prazoConclusao: 45,
    precoMinimo: 500,
    precoMaximo: 1500,
    voluntario: false,
    status: "PUBLICADO",
    dataHoraCriacao: "2021-11-24T15:25:36.655Z",
    dataHoraInicio: null,
    dataHoraFim: null,
    timestamp: "2021-11-25T14:22:12.666Z",
    dataHoraUltimaAtualizacao: "2021-11-25T02:25:03.403Z",
    type: "projetos",
    version: "1"
  },
  {
    score: 1,
    id: 2,
    nome: "Projeto Morning Show 2",
    descricao: "Uma descrição detalhada do projeto 2 aqui",
    areaInteresse: "Tecnologia da Informação",
    subareas: ["Desenvolvimento Web", "Desenvolvimento Mobile"],
    nivelExperiencia: "ESPECIALISTA",
    habilidadesExigidas: ["Node.js", "Javascript"],
    dataInicioEstimada: "2022-01-01",
    prazoConclusao: 45,
    precoMinimo: 1500,
    precoMaximo: 3500,
    voluntario: false,
    status: "PUBLICADO",
    dataHoraCriacao: "2021-11-24T15:25:36.655Z",
    dataHoraInicio: null,
    dataHoraFim: null,
    timestamp: "2021-11-25T14:22:12.666Z",
    dataHoraUltimaAtualizacao: "2021-11-25T02:25:03.403Z",
    type: "projetos",
    version: "1"
  },
  {
    score: 1,
    id: 3,
    nome: "Projeto Morning Show 3",
    descricao: "Uma descrição detalhada do projeto 2 aqui",
    areaInteresse: "Tecnologia da Informação",
    subareas: ["Desenvolvimento Web", "Desenvolvimento Mobile"],
    nivelExperiencia: "ESPECIALISTA",
    habilidadesExigidas: ["Node.js", "Javascript"],
    dataInicioEstimada: "2022-01-01",
    prazoConclusao: 45,
    precoMinimo: 0,
    precoMaximo: 0,
    voluntario: true,
    status: "PUBLICADO",
    dataHoraCriacao: "2021-11-24T15:25:36.655Z",
    dataHoraInicio: null,
    dataHoraFim: null,
    timestamp: "2021-11-25T14:22:12.666Z",
    dataHoraUltimaAtualizacao: "2021-11-25T02:25:03.403Z",
    type: "projetos",
    version: "1"
  },
]